services:
  web:
    image: linkuankuan/week1:latest
    restart: always
    expose:
      - "8000"
    env_file:
      - .env
    # --- 限制資源 ---
    deploy:
      resources:
        limits:
          memory: 350M # 每個分身最多用 350MB，兩個剛好 700MB
    # ----------------------

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"  # 新增 443 埠
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # 關鍵：讓容器讀取 EC2 上的憑證
    depends_on:
      - web